# Generated by Django 3.2.5 on 2021-11-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='sources/logo'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency.source'),
        ),
    ]
