# Generated by Django 3.2.5 on 2021-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20211117_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='logo',
        ),
        migrations.AddField(
            model_name='source',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='sources/logo'),
        ),
    ]
