version: "3"

services:

  backend:
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:5050"
    env_file:
      - .env

volumes:
  db_data: {}
